main: fr.td8.minetrace.MinetraceMain
name: MineTrace
version: 0.0.1
author: td8.subset(alf)
description: rien que pour Pierre-Antoine
commands:
  trace:
    description: Contrôle le lancement et l'arrêt trace
    usage: /trace <start|stop|write>
    permission: minetrace.trace
    permission: Désolé, mais tu n'es pas... un traceur (ça sonne bien non ?)